# Generated by Django 2.0.6 on 2018-06-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_profile_have_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='have_edited',
            field=models.IntegerField(default=0),
        ),
    ]
