# Generated by Django 2.0.6 on 2018-06-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180625_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(default='There is no introduction'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('UNKNOWN', 'unknown')], default='Unknown', max_length=1),
        ),
    ]
